In [1]:
#upload dataset (train.csv)

from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

In [5]:
#read the file

import pandas as pd

df=pd.read_csv("train.csv")

In [7]:
#check dataset

#df.shape
#df.head()
#df.info()

In [9]:
#check missing values

df.isnull().sum().sort_values(ascending=False).count()

np.int64(81)

In [12]:
#remove columns with too many values

df.dropna(axis=1, thresh=1000)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [14]:
# fill remaining values
# for numeric column fill with median

df = df.fillna(df.median(numeric_only=True))

# this ensure dataset has no missing values for model training

In [35]:
# select simple feature as this is a beginner project

features = [
    "GrLivArea",
    "BedroomAbvGr",
    "FullBath",
    "GarageCars",
    "OverallQual"
]
x = df[features]
y = df["SalePrice"]

In [36]:
#split data for training and testing

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# 80% data → training
# 20% data → testing

In [37]:
# train the model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

# this step is where the model actually learns patterns from data

LinearRegression()

In [38]:
# make predictions

predictions = model.predict(x_test)

predictions[:5]

array([133874.28011031, 294805.72807698, 136724.28397356, 190511.03542467,
       293579.85578181])

In [39]:
# evaluate the model

from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, predictions)
rsme = np.sqrt(mse)
print(rsme)

# lower value better model

41832.236679301815

In [40]:
x.head()

   GrLivArea  BedroomAbvGr  FullBath  GarageCars  OverallQual
0       1710             3         2           2            7
1       1262             3         2           2            6
2       1786             3         2           2            7
3       1717             3         1           3            7
4       2198             4         2           3            8

In [43]:
import pandas as pd

sample_house = pd.DataFrame(
    [[1710,3,2,2,7]],
    columns=[
        "GrLivArea",
        "BedroomAbvGr",
        "FullBath",
        "GarageCars",
        "OverallQual"
    ]
)

model.predict(sample_house)

prediction = model.predict(sample_house)

print("Predicted House Price: $", round(prediction[0],2))

Predicted House Price: $ 218218.56